version: '3.8'

services:
  ubuntu:
    build: ./ubuntu
    ports:
      - "2223:22"
      - "5901:5900"
    restart: always

  debian:
    build: ./debian
    ports:
      - "2224:22"
      - "5902:5900"
    restart: always

  kali:
    build: ./kali
    ports:
      - "2225:22"
      - "5903:5900"
    restart: always
